In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [18]:
from sklearn.datasets import make_classification

In [19]:
## Create datasets
X,y=make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=42)

In [20]:
pd.DataFrame(X)

0         1         2         3         4         5         6  \
0    0.964799 -0.066449  0.986768 -0.358079  0.997266  1.181890 -1.615679   
1   -0.916511 -0.566395 -1.008614  0.831617 -1.176962  1.820544  1.752375   
2   -0.109484 -0.432774 -0.457649  0.793818 -0.268646 -1.836360  1.239086   
3    1.750412  2.023606  1.688159  0.006800 -1.607661  0.184741 -2.619427   
4   -0.224726 -0.711303 -0.220778  0.117124  1.536061  0.597538  0.348645   
..        ...       ...       ...       ...       ...       ...       ...   
995 -1.367638  1.462255 -1.154918 -0.290454 -0.413424  0.032396  1.545490   
996 -1.514876 -3.221016 -1.300744  0.395599 -0.527994  1.353069  1.777506   
997  1.674633  1.754933  1.586154  0.018402 -1.514470  0.321593 -2.417694   
998 -0.778609 -0.835689 -0.194842  1.097220  0.180071 -0.272933 -0.533188   
999  0.248454 -1.003439  0.360460 -0.331352  1.389764 -1.345210 -0.740875   

            7         8         9  
0   -1.210161 -0.628077  1.227274  
1   -0.984534  0.363896  0.209470  
2   -0.246383 -1.058145 -0.297376  
3   -0.357445 -1.473127 -0.190039  
4   -0.939156  0.175915  0.236224  
..        ...       ...       ...  
995  1.428760  1.687092  1.072542  
996 -1.680870  1.798510  0.034272  
997  0.692723 -1.503850  0.225264  
998 -0.497354  2.472138  0.867187  
999  0.773240  0.185734  1.416412  

[1000 rows x 10 columns]

In [21]:
y

array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,

In [22]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=42)


In [23]:
# Model training
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression()

In [24]:
logistic.fit(X_train,y_train)

LogisticRegression()

In [25]:
y_pred=logistic.predict(X_test)
print(y_pred)

[0 1 0 1 0 1 0 0 0 0 0 1 0 1 0 0 1 1 1 1 0 0 1 0 0 1 0 0 1 1 1 1 0 0 0 0 1
 1 1 1 0 1 1 0 0 0 1 1 1 1 0 1 0 0 1 0 1 0 1 0 1 0 0 1 1 1 0 0 1 1 1 1 1 0
 1 0 0 1 0 1 0 0 1 0 1 0 0 0 0 1 1 1 1 1 1 1 0 0 1 0 1 0 1 0 0 1 0 1 1 1 1
 1 1 1 1 0 0 1 0 0 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 0 0 1 0 0 1 0 1 1 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 1 1 1 1 1 1 1
 0 0 0 0 1 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 1 1 1 0 0 0 0 0 1 0 1 0 1 1 0
 0 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 0 1 0 1 0 1 1 1 0 0 1 1 1 1
 0 1 0 1 1 0 0 0 1 1 0 1 1 0 0 1 0 0 0 0 1 1 0 1 0 1 1 1 0 0 1 0 1 1 0 1 1
 1 1 1 0]


In [26]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [28]:
score=accuracy_score(y_test,y_pred)
print(score)
cm=confusion_matrix(y_test,y_pred)
print(cm)
cr=classification_report(y_test,y_pred)
print(cr)


0.8466666666666667
[[118  17]
 [ 29 136]]
              precision    recall  f1-score   support

           0       0.80      0.87      0.84       135
           1       0.89      0.82      0.86       165

    accuracy                           0.85       300
   macro avg       0.85      0.85      0.85       300
weighted avg       0.85      0.85      0.85       300



Logistic regression for multi class classification


In [53]:
## Create datasets
X,y=make_classification(n_samples=1000,n_features=10,n_informative=3,n_classes=3,random_state=42)

In [54]:
X

array([[ 0.7715326 , -1.47433614,  2.19664605, ...,  0.68174341,
         1.08996189,  0.96250289],
       [ 1.85838284, -3.68087983,  0.22749588, ..., -0.47417818,
         1.34113888, -0.77177196],
       [-0.98724764,  1.53916836,  0.5859042 , ..., -0.32202815,
        -1.45103394,  1.32543211],
       ...,
       [-1.227082  ,  1.65602784,  0.47263035, ..., -0.8634936 ,
        -1.83932326, -0.03120349],
       [ 1.28527572, -0.29715202, -0.67172079, ..., -1.31544131,
         2.85446468,  1.3094441 ],
       [-0.75428048,  0.88516075, -1.6728939 , ..., -2.0362205 ,
        -1.43989584,  0.04749347]])

In [55]:
y

array([1, 2, 1, 1, 2, 1, 1, 0, 2, 2, 2, 0, 1, 0, 2, 1, 2, 1, 0, 1, 1, 1,
       2, 2, 1, 2, 2, 0, 1, 2, 0, 1, 0, 2, 0, 1, 0, 0, 2, 0, 1, 0, 2, 1,
       2, 0, 2, 0, 2, 0, 0, 0, 2, 1, 1, 1, 1, 2, 0, 0, 2, 1, 0, 0, 1, 2,
       0, 2, 2, 1, 0, 1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0,
       0, 1, 1, 2, 1, 0, 1, 2, 0, 2, 0, 0, 2, 1, 0, 2, 0, 2, 2, 0, 2, 0,
       0, 0, 0, 2, 1, 2, 1, 0, 2, 0, 0, 2, 1, 0, 2, 1, 0, 0, 2, 2, 0, 0,
       0, 2, 1, 2, 2, 0, 2, 0, 1, 2, 1, 2, 1, 1, 2, 0, 0, 1, 0, 2, 0, 0,
       0, 1, 1, 2, 1, 2, 2, 0, 0, 0, 1, 1, 0, 2, 1, 2, 2, 2, 1, 1, 0, 2,
       1, 0, 2, 1, 2, 1, 2, 0, 1, 1, 0, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 2,
       1, 2, 1, 1, 0, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 0, 2, 2, 2, 0,
       2, 0, 1, 1, 2, 1, 2, 2, 2, 2, 0, 1, 0, 0, 0, 0, 2, 2, 2, 1, 1, 1,
       0, 2, 0, 0, 1, 0, 2, 0, 1, 2, 2, 2, 1, 2, 1, 0, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 0, 0, 0, 2, 1, 1, 1, 1, 2, 1, 2, 2, 1, 2, 1, 0, 0, 2, 2,
       2, 1, 1, 1, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 1,

In [56]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=42)


In [60]:
from sklearn.linear_model import LogisticRegression
regression=LogisticRegression(multi_class='ovr')
logistic.fit(X_train,y_train)
y_pred=logistic.predict(X_test)

In [64]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
score=accuracy_score(y_pred,y_test)
cm=confusion_matrix(y_pred,y_test)
cr=classification_report(y_pred,y_test)

In [66]:
print('accuracy',score)
print(cm)
print('classification_report',cr)


accuracy 0.7033333333333334
[[76 25  2]
 [20 48 12]
 [ 7 23 87]]
classification_report               precision    recall  f1-score   support

           0       0.74      0.74      0.74       103
           1       0.50      0.60      0.55        80
           2       0.86      0.74      0.80       117

    accuracy                           0.70       300
   macro avg       0.70      0.69      0.69       300
weighted avg       0.72      0.70      0.71       300



In [68]:
## Hyperparameter and cross validation
model=LogisticRegression(multi_class='ovr')
penalty=['l1','l2','elasticnet']
c_values=[100,10,1.0,0.1,0.01]
solver=['newton-cg','lbfgs','liblinear','sag','saga']


In [69]:
params=dict(penalty=penalty,C=c_values,solver=solver)

In [71]:
##GridsearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold()
grid=GridSearchCV(estimator=model,param_grid=params,scoring='accuracy',cv=cv,n_jobs=-1)



In [72]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(multi_class='ovr'), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [73]:
grid.fit(X_train,y_train)

d:\ML\venv\lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning: 
200 fits failed out of a total of 375.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "d:\ML\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\ML\venv\lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "d:\ML\venv\lib\site-packages\sklearn\linear_model\_logistic.py", line 1194, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "d:\ML\venv\lib\site-packages\sklearn\linear_m

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(multi_class='ovr'), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [74]:
grid.best_params_

{'C': 0.01, 'penalty': 'l1', 'solver': 'saga'}

In [75]:
grid.best_score_

np.float64(0.6385714285714286)

In [76]:
y_pred=grid.predict(X_test)

In [77]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
score=accuracy_score(y_pred,y_test)
cm=confusion_matrix(y_pred,y_test)
cr=classification_report(y_pred,y_test)

In [78]:
print('accuracy',score)
print(cm)
print('classification_report',cr)


accuracy 0.6733333333333333
[[86 44  3]
 [ 7 23  5]
 [10 29 93]]
classification_report               precision    recall  f1-score   support

           0       0.83      0.65      0.73       133
           1       0.24      0.66      0.35        35
           2       0.92      0.70      0.80       132

    accuracy                           0.67       300
   macro avg       0.67      0.67      0.63       300
weighted avg       0.80      0.67      0.72       300



In [79]:
## Randamized search cv

from sklearn.model_selection import RandomizedSearchCV

In [80]:
randomcv=RandomizedSearchCV(estimator=model,param_distributions=params,scoring='accuracy',cv=5)

In [81]:
randomcv.fit(X_train,y_train)

d:\ML\venv\lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
d:\ML\venv\lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
d:\ML\venv\lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
d:\ML\venv\lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 

RandomizedSearchCV(cv=5, estimator=LogisticRegression(multi_class='ovr'),
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [84]:
randomcv.best_params_

{'solver': 'saga', 'penalty': 'l1', 'C': 0.1}

In [83]:
randomcv.best_score_

np.float64(0.6328571428571428)

In [85]:
y_pred=randomcv.predict(X_test)

In [86]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
score=accuracy_score(y_pred,y_test)
cm=confusion_matrix(y_pred,y_test)
cr=classification_report(y_pred,y_test)

In [87]:
print('accuracy',score)
print(cm)
print('classification_report',cr)


accuracy 0.6833333333333333
[[80 35  3]
 [15 35  8]
 [ 8 26 90]]
classification_report               precision    recall  f1-score   support

           0       0.78      0.68      0.72       118
           1       0.36      0.60      0.45        58
           2       0.89      0.73      0.80       124

    accuracy                           0.68       300
   macro avg       0.68      0.67      0.66       300
weighted avg       0.74      0.68      0.70       300

