In [1]:
!pip install numpy

In [2]:
import numpy as np

In [4]:
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [7]:
arr2=np.array((1,2,3,4,5,6))

In [8]:
arr2

array([1, 2, 3, 4, 5, 6])

In [5]:
print(type(arr1))

<class 'numpy.ndarray'>


In [6]:
arr1.shape

(5,)

In [11]:
np.arange(1,6,2)

array([1, 3, 5])

In [12]:
np.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [14]:
arr1.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [20]:
a1=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(a1)
print(a1.shape)

[[1 2 3 4 5]
 [6 7 8 9 0]]
(2, 5)


In [22]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [27]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
##Vectorized operations add,sub and so on

In [29]:
#universal function
arr1

array([1, 2, 3, 4, 5])

In [30]:
np.sqrt(arr1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [31]:
np.log(arr1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [37]:
## array slicing and index operation
arr1=np.array([[1,2,3,4,5],[6,7,8,9,4],[3,4,5,6,7]])

In [38]:
arr1

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 4],
       [3, 4, 5, 6, 7]])

In [39]:
arr1.shape

(3, 5)

In [41]:
arr1[1:,1:]

array([[7, 8, 9, 4],
       [4, 5, 6, 7]])

In [43]:
#modify the array
arr1[0][0]=100

In [44]:
arr1

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,   4],
       [  3,   4,   5,   6,   7]])

In [45]:
arr1[0:]=100

In [50]:
[[arr1<99]]

[[array([[False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False]])]]

In [ ]:
## Statistical concepts

In [ ]:
#pandas

In [51]:
import pandas as pd

In [52]:
pd.Series(arr2)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int32

In [54]:
data={'a':1,'b':2,'c':3,'d':4}
pd.Series(data)

a    1
b    2
c    3
d    4
dtype: int64

In [56]:
d=[12,3,45,67]
i=['a','b','c','d']
pd.Series(data=d,index=i)

a    12
b     3
c    45
d    67
dtype: int64

In [57]:
datas={
    'Name':['Nagendra','Manju'],
    'Age':[23,24],
    'City':['Chintamani','Tumkur']
}

In [99]:
df=pd.DataFrame(datas)

In [100]:
df

Name  Age        City
0  Nagendra   23  Chintamani
1     Manju   24      Tumkur

In [63]:
df['Name']

0    Nagendra
1       Manju
Name: Name, dtype: object

In [64]:
df.loc[0]

Name      Nagendra
Age             23
City    Chintamani
Name: 0, dtype: object

In [65]:
df.iloc[0][1]

C:\Users\nagen\AppData\Local\Temp\ipykernel_15616\2309508539.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][1]


23

In [66]:
df.iloc[1,1:]

Age         24
City    Tumkur
Name: 1, dtype: object

In [68]:
df.at[1,'Name']

'Manju'

In [70]:
df.iat[1,1]

24

In [83]:
df['Salary']=[12,23]

In [76]:
df

Name  Age        City  Salary
0  Nagendra   23  Chintamani      12
1     Manju   24      Tumkur      23

In [81]:
df.drop('Salary',axis=1,inplace=True)

In [84]:
df

Name  Age        City  Salary
0  Nagendra   23  Chintamani      12
1     Manju   24      Tumkur      23

In [85]:
df['Salary']=df['Salary']+1

In [95]:
df

Name  Age        City
0  Nagendra   23  Chintamani
1     Manju   24      Tumkur

In [96]:
df=df.drop(0,inplace=True)

In [97]:
df

In [98]:
df

In [101]:
df.rename(columns={'Name':'Names'})

Names  Age        City
0  Nagendra   23  Chintamani
1     Manju   24      Tumkur

In [103]:
[df.isna()]

[    Name    Age   City
 0  False  False  False
 1  False  False  False]

In [104]:
df.dtypes

Name    object
Age      int64
City    object
dtype: object

In [106]:
df

Name  Age        City
0  Nagendra   23  Chintamani
1     Manju   24      Tumkur

In [107]:
df['Ages']=df['Age'].apply(lambda x:x*2)

In [108]:
df

Name  Age        City  Ages
0  Nagendra   23  Chintamani    46
1     Manju   24      Tumkur    48